/**
 * The DDL fixture is the one copy of the proposed export schema (DESK_FRAME3_SPEC
 * §12.9, S-04; FRAME3_API_PLAN.md §1.9, R-02): `PIPELINE_DDL` equals
 * api/static/snowflake_proposed.sql byte for byte, and the module is exactly what
 * web/scripts/gen-ddl-fixture.mjs writes from it, so neither side can drift alone.
 * The .sql file is read with fs, never imported: no file under web/ imports a
 * .sql file (tests/test_desk_v2_pipeline.py scans web/ for one).
 */
import { describe, expect, it } from "vitest";
import { escapeTemplate, render } from "../../../scripts/gen-ddl-fixture.mjs";
import { PIPELINE_DDL } from "./pipeline-ddl";

const MODULE = Object.values(import.meta.glob<string>("./pipeline-ddl.ts", { query: "?raw", import: "default", eager: true }))[0];

/** The file's bytes, read with fs from the repository (vitest runs in web/; there is no
 * @types/node here, so each node module is typed at the call). */
async function sqlBytes(): Promise<Uint8Array> {
  const fs = (await import("node:fs" as string)) as { readFileSync(path: string): Uint8Array };
  const path = (await import("node:path" as string)) as { resolve(...parts: string[]): string };
  const proc = (await import("node:process" as string)) as { cwd(): string };
  return fs.readFileSync(path.resolve(proc.cwd(), "..", "api", "static", "snowflake_proposed.sql"));
}

describe("the DDL fixture (S-04, R-02)", () => {
  it("exports api/static/snowflake_proposed.sql byte for byte", async () => {
    const file = await sqlBytes();
    const served = new TextEncoder().encode(PIPELINE_DDL);
    expect(served.length).toBe(file.length);
    expect(served.every((b, i) => b === file[i])).toBe(true);
    expect(PIPELINE_DDL.split("\n")[0]).toBe(
      "-- PROPOSED Snowflake export schema (not the current SQLite layout); nothing in this project creates it.",
    );
  });

  it("is the module the generator writes, byte for byte", async () => {
    const sql = new TextDecoder("utf-8", { fatal: true }).decode(await sqlBytes());
    expect(MODULE).toBe(render(sql));
    expect(MODULE.startsWith("/**\n * GENERATED by web/scripts/gen-ddl-fixture.mjs")).toBe(true);
  });

  it("escapes what a template literal would read: backslashes, backticks and ${", () => {
    const tricky = "a \\ b ` c ${d} e $ f {g}";
    const body = escapeTemplate(tricky);
    expect(body).toBe("a \\\\ b \\` c \\${d} e $ f {g}");
    expect(new Function(`return \`${body}\`;`)()).toBe(tricky);
  });
});
