"""scripts/gen_nyse_holidays.py — the NYSE holiday tables for every stored year (desk/frame-3-api, S-12).

docs/desk/FRAME3_API_PLAN.md §1.11 N7 (ruled S-12, R-03). api/calendar.py
held holiday lists for 2024–2027 only, and "a missing year degrades to
weekends-only": a bond-calendar window reaching 2023 counted 2023-12-25 as a
missing session. This writes the lists for 1962 (DGS10's first year) through
2023 into api/calendar.py and its lean copy src/market_data/session.py, which
tests/test_market_session.py keeps equal.

The source is exchange_calendars' XNYS holiday **definitions**, never
"weekdays minus sessions": `regular_holidays.holidays(start, end)`, the
rule-based holidays bounded to the range, plus `adhoc_holidays`, the one-off
closings, filtered to the same range; weekdays only. That matters before 1970:
pandas' holiday calendar starts at 1970-01-01, so exchange_calendars' own XNYS
sessions keep every regular holiday of 1962–1969 as a session (1962-12-25
among them), while the definitions name them. Before 1970 these tables are the
authority; parity with the engine's sessions holds from 1970-01-01.

The web's copy, web/src/screens/desk/positions/sessions.ts (a position's day
count, DESK_FRAME3_SPEC §9), is written from the fresh api/calendar.py, every
year of its HOLIDAYS, so it cannot drift from the Python tables;
sessions.test.ts holds it equal year for year.

    python scripts/gen_nyse_holidays.py          # rewrite the 1962–2023 lines of both tables, then the web's table
    python scripts/gen_nyse_holidays.py --check  # exit 1 when a file differs from a fresh run

The 2024–2027 lines stay as they are (the published NYSE schedule). Needs the
API venv (exchange_calendars 4.13.2, pinned in requirements-api.txt); the
modules it writes stay stdlib-only.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIRST, LAST = 1962, 2023
TARGETS = (ROOT / "api" / "calendar.py", ROOT / "src" / "market_data" / "session.py")
MARKER = ("    # 1962–2023: generated by scripts/gen_nyse_holidays.py from exchange_calendars' XNYS holiday\n"
          "    # definitions (bounded regular_holidays + adhoc_holidays, weekdays; plan S-12, R-03).\n")
BLOCK = re.compile(r"(HOLIDAYS: dict\[int, set\[date\]\] = \{\n)(.*?)(\n\})", re.S)
WEB = ROOT / "web" / "src" / "screens" / "desk" / "positions" / "sessions.ts"
WEB_MARKER = ("  // Generated by scripts/gen_nyse_holidays.py: api/calendar.py's HOLIDAYS, every year (1962–2023 from\n"
              "  // exchange_calendars' XNYS holiday definitions, 2024–2027 the published NYSE schedule).\n")
WEB_BLOCK = re.compile(r"(const HOLIDAYS: Readonly<Record<number, readonly string\[\]>> = \{\n)(.*?)(\n\};)", re.S)


def holidays_by_year(first: int = FIRST, last: int = LAST) -> dict[int, list[date]]:
    """Each year's NYSE holidays from the XNYS definitions, each year bounded to itself."""
    import exchange_calendars as xcals
    import pandas as pd

    cal = xcals.get_calendar("XNYS", start=f"{first}-01-01", end=f"{last}-12-31")
    out: dict[int, list[date]] = {}
    for year in range(first, last + 1):
        lo, hi = pd.Timestamp(f"{year}-01-01"), pd.Timestamp(f"{year}-12-31")
        regular = list(cal.regular_holidays.holidays(start=lo, end=hi))
        adhoc = [pd.Timestamp(d) for d in cal.adhoc_holidays if lo <= pd.Timestamp(d) <= hi]
        out[year] = sorted({d.date() for d in regular + adhoc if d.weekday() < 5})
    return out


def _line(year: int, days: list[date]) -> str:
    return f"    {year}: {{" + ", ".join(f"date({d.year}, {d.month}, {d.day})" for d in days) + "},"


def rendered(text: str, table: dict[int, list[date]]) -> str:
    """`text` with its HOLIDAYS block's generated lines replaced by `table`'s."""
    m = BLOCK.search(text)
    if not m:
        raise SystemExit("no HOLIDAYS block found")
    kept = [ln for ln in m.group(2).split("\n")
            if ln.strip() and not ln.strip().startswith("#") and int(ln.strip().split(":")[0]) > LAST]
    body = MARKER + "\n".join(_line(y, table[y]) for y in sorted(table)) + "\n" + "\n".join(kept)
    return text[:m.start(2)] + body + text[m.end(2):]


def calendar_table(text: str) -> dict[int, list[date]]:
    """Every year of the HOLIDAYS block in api/calendar.py's `text`, sorted."""
    m = BLOCK.search(text)
    if not m:
        raise SystemExit("no HOLIDAYS block found")
    out: dict[int, list[date]] = {}
    for year, body in re.findall(r"(\d{4}):\s*\{([^}]*)\}", m.group(2)):
        out[int(year)] = sorted(date(int(y), int(mo), int(d))
                                for y, mo, d in re.findall(r"date\((\d{4}),\s*(\d{1,2}),\s*(\d{1,2})\)", body))
    return out


def rendered_web(text: str, calendar_text: str) -> str:
    """sessions.ts's `text` with its HOLIDAYS table replaced by api/calendar.py's, every year."""
    m = WEB_BLOCK.search(text)
    if not m:
        raise SystemExit("no HOLIDAYS table found in sessions.ts")
    table = calendar_table(calendar_text)
    lines = [f"  {y}: [" + ", ".join(f'"{d.isoformat()}"' for d in table[y]) + "]," for y in sorted(table)]
    return text[:m.start(2)] + WEB_MARKER + "\n".join(lines) + text[m.end(2):]


def outputs(table: dict[int, list[date]]) -> dict[Path, str]:
    """Each file's fresh text: the two Python tables with `table`'s years, then the
    web's table from the fresh api/calendar.py."""
    out = {path: rendered(path.read_text(), table) for path in TARGETS}
    out[WEB] = rendered_web(WEB.read_text(), out[TARGETS[0]])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when a file differs from a fresh run")
    a = ap.parse_args()
    table = holidays_by_year()
    stale = []
    for path, new in outputs(table).items():
        if new != path.read_text():
            stale.append(path.relative_to(ROOT))
            if not a.check:
                path.write_text(new)
    n = sum(len(v) for v in table.values())
    if a.check:
        print("up to date" if not stale else f"differs from a fresh run: {', '.join(map(str, stale))}")
        return 1 if stale else 0
    print(f"{FIRST}–{LAST}: {n} holidays ({sum(len(v) for y, v in table.items() if y < 1970)} before 1970); "
          f"rewrote {', '.join(map(str, stale)) or 'nothing'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
