"""scripts/lock_api_requirements.py — pin the API image's dependency set.

The image used to install `requirements-api.txt` unpinned, so an image built
next month ran whatever resolved that day: pandas 4 alone changes a concat
default this code relies on. This walks the installed metadata of the virtual
environment the branch's tests ran against and prints one `name==version` line
per package in the API's dependency closure.

    .venv/bin/python scripts/lock_api_requirements.py > requirements-api.lock

Stdlib plus `packaging` (already installed); no new tooling. yfinance is not a
root: the API never calls Yahoo (fix/prelaunch-1), and the refresh pipeline
installs it from its own requirements file.
"""

from __future__ import annotations

import importlib.metadata as md
import sys
from datetime import date

from packaging.markers import default_environment
from packaging.requirements import Requirement

# requirements-api.txt's roots. uvicorn carries its "standard" extra, the one
# the Dockerfile installs (uvloop, httptools, watchfiles, PyYAML).
ROOTS: list[tuple[str, set[str]]] = [
    ("fastapi", set()),
    ("uvicorn", {"standard"}),
    ("httpx", set()),
    ("websockets", set()),
    ("pandas", set()),
    ("numpy", set()),
    ("scikit-learn", set()),
    ("riskfolio-lib", set()),
    ("anthropic", set()),
]


def closure() -> dict[str, str]:
    seen: dict[str, str] = {}
    missing: list[str] = []

    def walk(name: str, extras: set[str]) -> None:
        key = name.lower().replace("_", "-")
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            missing.append(name)
            return
        if key in seen and not extras:
            return
        seen[key] = dist.version
        for raw in dist.requires or []:
            req = Requirement(raw)
            if req.marker is not None:
                env = {**default_environment(), "extra": ""}
                if not any(req.marker.evaluate({**env, "extra": e}) for e in (extras or {""})):
                    continue
            walk(req.name, set(req.extras))

    for name, extras in ROOTS:
        walk(name, extras)
    if missing:
        print(f"# WARNING: not installed in this environment: {', '.join(sorted(set(missing)))}", file=sys.stderr)
    return seen


def main() -> None:
    pins = closure()
    print(
        "# requirements-api.lock — the exact dependency set the API image installs.\n"
        "#\n"
        f"# Generated by scripts/lock_api_requirements.py on {date.today().isoformat()} from the\n"
        "# virtual environment this branch's tests ran against, so an image built later\n"
        "# runs the versions that were tested rather than whatever resolves that day.\n"
        "#\n"
        "# Roots: requirements-api.txt minus yfinance (the API never calls Yahoo since\n"
        "# fix/prelaunch-1). Regenerate after changing requirements-api.txt."
    )
    for name, version in sorted(pins.items()):
        print(f"{name}=={version}")


if __name__ == "__main__":
    main()
