"""scripts/lock_api_requirements.py — pin the API image's dependency set.

The image used to install `requirements-api.txt` unpinned, so an image built
next month ran whatever resolved that day: pandas 4 alone changes a concat
default this code relies on. This takes `pip freeze` of the virtual environment
the branch's tests ran against and keeps the lines in the API's dependency
closure: the closure comes from the installed packages' own metadata (what
each one requires), the pins from pip freeze, and the two must agree.

    .venv/bin/python scripts/lock_api_requirements.py > requirements-api.lock

pip, the stdlib and `packaging`, all already installed; no new tooling.
yfinance is not a root: the API never calls Yahoo (fix/prelaunch-1), and the
refresh pipeline installs it from its own requirements file.
"""

from __future__ import annotations

import importlib.metadata as md
import re
import subprocess
import sys
from datetime import date

from packaging.markers import default_environment
from packaging.requirements import Requirement

# requirements-api.txt's roots. uvicorn carries its "standard" extra, the one
# the Dockerfile installs (uvloop, httptools, watchfiles, PyYAML).
ROOTS: list[tuple[str, set[str]]] = [
    ("fastapi", set()),
    ("uvicorn", {"standard"}),
    ("httpx", set()),
    ("websockets", set()),
    ("pandas", set()),
    ("numpy", set()),
    ("scikit-learn", set()),
    ("riskfolio-lib", set()),
    ("anthropic", set()),
]


def closure() -> dict[str, str]:
    seen: dict[str, str] = {}
    missing: list[str] = []

    def walk(name: str, extras: set[str]) -> None:
        key = name.lower().replace("_", "-")
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            missing.append(name)
            return
        if key in seen and not extras:
            return
        seen[key] = dist.version
        for raw in dist.requires or []:
            req = Requirement(raw)
            if req.marker is not None:
                env = {**default_environment(), "extra": ""}
                if not any(req.marker.evaluate({**env, "extra": e}) for e in (extras or {""})):
                    continue
            walk(req.name, set(req.extras))

    for name, extras in ROOTS:
        walk(name, extras)
    if missing:
        print(f"# WARNING: not installed in this environment: {', '.join(sorted(set(missing)))}", file=sys.stderr)
    return seen


def _key(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def freeze() -> dict[str, str]:
    """`pip freeze --all` of this interpreter: normalized name -> the line."""
    out = subprocess.run([sys.executable, "-m", "pip", "freeze", "--all"], capture_output=True, text=True, check=True).stdout
    lines: dict[str, str] = {}
    for line in out.splitlines():
        if "==" in line and not line.startswith(("-e", "#")):
            lines[_key(line.split("==", 1)[0])] = line.strip()
    return lines


def main() -> None:
    pins = closure()
    frozen = freeze()
    lines = []
    for name, version in sorted(pins.items()):
        line = frozen.get(_key(name))
        if line is None or line.split("==", 1)[1] != version:
            sys.exit(f"pip freeze and the installed metadata disagree on {name}: {line!r} vs {version}")
        lines.append(line)
    print(
        "# requirements-api.lock — the exact dependency set the API image installs.\n"
        "#\n"
        f"# Generated by scripts/lock_api_requirements.py on {date.today().isoformat()}: pip freeze\n"
        "# of the virtual environment this branch's tests ran against, kept to the API's\n"
        "# dependency closure, so an image built later runs the versions that were tested\n"
        "# rather than whatever resolves that day.\n"
        "#\n"
        "# Roots: requirements-api.txt minus yfinance (the API never calls Yahoo since\n"
        "# fix/prelaunch-1). Regenerate after changing requirements-api.txt."
    )
    for line in sorted(lines, key=lambda l: _key(l.split("==", 1)[0])):
        print(line)


if __name__ == "__main__":
    main()
