"""api/calendar.py — NYSE session calendar for freshness verdicts (2026-09-06).

Pure functions, no network. Holidays and early closes are the published NYSE
schedule for 2024–2027; extend the tables when the exchange publishes the
next year (a missing year degrades to weekends-only, never to a crash). The
holidays of 1962–2023, every year the store holds, are generated by
scripts/gen_nyse_holidays.py from exchange_calendars' XNYS definitions
(desk/frame-3-api, S-12); before 1970 these tables are the authority, where
exchange_calendars' own sessions keep the regular holidays open.
Times are America/New_York; every function accepts and returns aware UTC
datetimes so callers never guess a zone.
"""

from __future__ import annotations

from datetime import date, datetime, time, timedelta, timezone
from zoneinfo import ZoneInfo

NY = ZoneInfo("America/New_York")

HOLIDAYS: dict[int, set[date]] = {
    # 1962–2023: generated by scripts/gen_nyse_holidays.py from exchange_calendars' XNYS holiday
    # definitions (bounded regular_holidays + adhoc_holidays, weekdays; plan S-12, R-03).
    1962: {date(1962, 1, 1), date(1962, 2, 22), date(1962, 4, 20), date(1962, 5, 30), date(1962, 7, 4), date(1962, 9, 3), date(1962, 11, 6), date(1962, 11, 22), date(1962, 12, 25)},
    1963: {date(1963, 1, 1), date(1963, 2, 22), date(1963, 4, 12), date(1963, 5, 30), date(1963, 7, 4), date(1963, 9, 2), date(1963, 11, 5), date(1963, 11, 25), date(1963, 11, 28), date(1963, 12, 25)},
    1964: {date(1964, 1, 1), date(1964, 2, 21), date(1964, 3, 27), date(1964, 5, 29), date(1964, 7, 3), date(1964, 9, 7), date(1964, 11, 3), date(1964, 11, 26), date(1964, 12, 25)},
    1965: {date(1965, 1, 1), date(1965, 2, 22), date(1965, 4, 16), date(1965, 5, 31), date(1965, 7, 5), date(1965, 9, 6), date(1965, 11, 2), date(1965, 11, 25), date(1965, 12, 24)},
    1966: {date(1966, 2, 22), date(1966, 4, 8), date(1966, 5, 30), date(1966, 7, 4), date(1966, 9, 5), date(1966, 11, 8), date(1966, 11, 24), date(1966, 12, 26)},
    1967: {date(1967, 1, 2), date(1967, 2, 22), date(1967, 3, 24), date(1967, 5, 30), date(1967, 7, 4), date(1967, 9, 4), date(1967, 11, 7), date(1967, 11, 23), date(1967, 12, 25)},
    1968: {date(1968, 1, 1), date(1968, 2, 12), date(1968, 2, 22), date(1968, 4, 9), date(1968, 4, 12), date(1968, 5, 30), date(1968, 6, 12), date(1968, 6, 19), date(1968, 6, 26), date(1968, 7, 4), date(1968, 7, 5), date(1968, 7, 10), date(1968, 7, 17), date(1968, 7, 24), date(1968, 7, 31), date(1968, 8, 7), date(1968, 8, 14), date(1968, 8, 21), date(1968, 8, 28), date(1968, 9, 2), date(1968, 9, 11), date(1968, 9, 18), date(1968, 9, 25), date(1968, 10, 2), date(1968, 10, 9), date(1968, 10, 16), date(1968, 10, 23), date(1968, 10, 30), date(1968, 11, 5), date(1968, 11, 11), date(1968, 11, 20), date(1968, 11, 28), date(1968, 12, 4), date(1968, 12, 11), date(1968, 12, 18), date(1968, 12, 25)},
    1969: {date(1969, 1, 1), date(1969, 2, 10), date(1969, 2, 21), date(1969, 3, 31), date(1969, 4, 4), date(1969, 5, 30), date(1969, 7, 4), date(1969, 7, 21), date(1969, 9, 1), date(1969, 11, 27), date(1969, 12, 25)},
    1970: {date(1970, 1, 1), date(1970, 2, 23), date(1970, 3, 27), date(1970, 7, 3), date(1970, 9, 7), date(1970, 11, 26), date(1970, 12, 25)},
    1971: {date(1971, 1, 1), date(1971, 2, 15), date(1971, 4, 9), date(1971, 5, 31), date(1971, 7, 5), date(1971, 9, 6), date(1971, 11, 25), date(1971, 12, 24)},
    1972: {date(1972, 2, 21), date(1972, 3, 31), date(1972, 5, 29), date(1972, 7, 4), date(1972, 9, 4), date(1972, 11, 7), date(1972, 11, 23), date(1972, 12, 25), date(1972, 12, 28)},
    1973: {date(1973, 1, 1), date(1973, 1, 25), date(1973, 2, 19), date(1973, 4, 20), date(1973, 5, 28), date(1973, 7, 4), date(1973, 9, 3), date(1973, 11, 22), date(1973, 12, 25)},
    1974: {date(1974, 1, 1), date(1974, 2, 18), date(1974, 4, 12), date(1974, 5, 27), date(1974, 7, 4), date(1974, 9, 2), date(1974, 11, 28), date(1974, 12, 25)},
    1975: {date(1975, 1, 1), date(1975, 2, 17), date(1975, 3, 28), date(1975, 5, 26), date(1975, 7, 4), date(1975, 9, 1), date(1975, 11, 27), date(1975, 12, 25)},
    1976: {date(1976, 1, 1), date(1976, 2, 16), date(1976, 4, 16), date(1976, 5, 31), date(1976, 7, 5), date(1976, 9, 6), date(1976, 11, 2), date(1976, 11, 25), date(1976, 12, 24)},
    1977: {date(1977, 2, 21), date(1977, 4, 8), date(1977, 5, 30), date(1977, 7, 4), date(1977, 7, 14), date(1977, 9, 5), date(1977, 11, 24), date(1977, 12, 26)},
    1978: {date(1978, 1, 2), date(1978, 2, 20), date(1978, 3, 24), date(1978, 5, 29), date(1978, 7, 4), date(1978, 9, 4), date(1978, 11, 23), date(1978, 12, 25)},
    1979: {date(1979, 1, 1), date(1979, 2, 19), date(1979, 4, 13), date(1979, 5, 28), date(1979, 7, 4), date(1979, 9, 3), date(1979, 11, 22), date(1979, 12, 25)},
    1980: {date(1980, 1, 1), date(1980, 2, 18), date(1980, 4, 4), date(1980, 5, 26), date(1980, 7, 4), date(1980, 9, 1), date(1980, 11, 4), date(1980, 11, 27), date(1980, 12, 25)},
    1981: {date(1981, 1, 1), date(1981, 2, 16), date(1981, 4, 17), date(1981, 5, 25), date(1981, 7, 3), date(1981, 9, 7), date(1981, 11, 26), date(1981, 12, 25)},
    1982: {date(1982, 1, 1), date(1982, 2, 15), date(1982, 4, 9), date(1982, 5, 31), date(1982, 7, 5), date(1982, 9, 6), date(1982, 11, 25), date(1982, 12, 24)},
    1983: {date(1983, 2, 21), date(1983, 4, 1), date(1983, 5, 30), date(1983, 7, 4), date(1983, 9, 5), date(1983, 11, 24), date(1983, 12, 26)},
    1984: {date(1984, 1, 2), date(1984, 2, 20), date(1984, 4, 20), date(1984, 5, 28), date(1984, 7, 4), date(1984, 9, 3), date(1984, 11, 22), date(1984, 12, 25)},
    1985: {date(1985, 1, 1), date(1985, 2, 18), date(1985, 4, 5), date(1985, 5, 27), date(1985, 7, 4), date(1985, 9, 2), date(1985, 9, 27), date(1985, 11, 28), date(1985, 12, 25)},
    1986: {date(1986, 1, 1), date(1986, 2, 17), date(1986, 3, 28), date(1986, 5, 26), date(1986, 7, 4), date(1986, 9, 1), date(1986, 11, 27), date(1986, 12, 25)},
    1987: {date(1987, 1, 1), date(1987, 2, 16), date(1987, 4, 17), date(1987, 5, 25), date(1987, 7, 3), date(1987, 9, 7), date(1987, 11, 26), date(1987, 12, 25)},
    1988: {date(1988, 1, 1), date(1988, 2, 15), date(1988, 4, 1), date(1988, 5, 30), date(1988, 7, 4), date(1988, 9, 5), date(1988, 11, 24), date(1988, 12, 26)},
    1989: {date(1989, 1, 2), date(1989, 2, 20), date(1989, 3, 24), date(1989, 5, 29), date(1989, 7, 4), date(1989, 9, 4), date(1989, 11, 23), date(1989, 12, 25)},
    1990: {date(1990, 1, 1), date(1990, 2, 19), date(1990, 4, 13), date(1990, 5, 28), date(1990, 7, 4), date(1990, 9, 3), date(1990, 11, 22), date(1990, 12, 25)},
    1991: {date(1991, 1, 1), date(1991, 2, 18), date(1991, 3, 29), date(1991, 5, 27), date(1991, 7, 4), date(1991, 9, 2), date(1991, 11, 28), date(1991, 12, 25)},
    1992: {date(1992, 1, 1), date(1992, 2, 17), date(1992, 4, 17), date(1992, 5, 25), date(1992, 7, 3), date(1992, 9, 7), date(1992, 11, 26), date(1992, 12, 25)},
    1993: {date(1993, 1, 1), date(1993, 2, 15), date(1993, 4, 9), date(1993, 5, 31), date(1993, 7, 5), date(1993, 9, 6), date(1993, 11, 25), date(1993, 12, 24)},
    1994: {date(1994, 2, 21), date(1994, 4, 1), date(1994, 4, 27), date(1994, 5, 30), date(1994, 7, 4), date(1994, 9, 5), date(1994, 11, 24), date(1994, 12, 26)},
    1995: {date(1995, 1, 2), date(1995, 2, 20), date(1995, 4, 14), date(1995, 5, 29), date(1995, 7, 4), date(1995, 9, 4), date(1995, 11, 23), date(1995, 12, 25)},
    1996: {date(1996, 1, 1), date(1996, 2, 19), date(1996, 4, 5), date(1996, 5, 27), date(1996, 7, 4), date(1996, 9, 2), date(1996, 11, 28), date(1996, 12, 25)},
    1997: {date(1997, 1, 1), date(1997, 2, 17), date(1997, 3, 28), date(1997, 5, 26), date(1997, 7, 4), date(1997, 9, 1), date(1997, 11, 27), date(1997, 12, 25)},
    1998: {date(1998, 1, 1), date(1998, 1, 19), date(1998, 2, 16), date(1998, 4, 10), date(1998, 5, 25), date(1998, 7, 3), date(1998, 9, 7), date(1998, 11, 26), date(1998, 12, 25)},
    1999: {date(1999, 1, 1), date(1999, 1, 18), date(1999, 2, 15), date(1999, 4, 2), date(1999, 5, 31), date(1999, 7, 5), date(1999, 9, 6), date(1999, 11, 25), date(1999, 12, 24)},
    2000: {date(2000, 1, 17), date(2000, 2, 21), date(2000, 4, 21), date(2000, 5, 29), date(2000, 7, 4), date(2000, 9, 4), date(2000, 11, 23), date(2000, 12, 25)},
    2001: {date(2001, 1, 1), date(2001, 1, 15), date(2001, 2, 19), date(2001, 4, 13), date(2001, 5, 28), date(2001, 7, 4), date(2001, 9, 3), date(2001, 9, 11), date(2001, 9, 12), date(2001, 9, 13), date(2001, 9, 14), date(2001, 11, 22), date(2001, 12, 25)},
    2002: {date(2002, 1, 1), date(2002, 1, 21), date(2002, 2, 18), date(2002, 3, 29), date(2002, 5, 27), date(2002, 7, 4), date(2002, 9, 2), date(2002, 11, 28), date(2002, 12, 25)},
    2003: {date(2003, 1, 1), date(2003, 1, 20), date(2003, 2, 17), date(2003, 4, 18), date(2003, 5, 26), date(2003, 7, 4), date(2003, 9, 1), date(2003, 11, 27), date(2003, 12, 25)},
    2004: {date(2004, 1, 1), date(2004, 1, 19), date(2004, 2, 16), date(2004, 4, 9), date(2004, 5, 31), date(2004, 6, 11), date(2004, 7, 5), date(2004, 9, 6), date(2004, 11, 25), date(2004, 12, 24)},
    2005: {date(2005, 1, 17), date(2005, 2, 21), date(2005, 3, 25), date(2005, 5, 30), date(2005, 7, 4), date(2005, 9, 5), date(2005, 11, 24), date(2005, 12, 26)},
    2006: {date(2006, 1, 2), date(2006, 1, 16), date(2006, 2, 20), date(2006, 4, 14), date(2006, 5, 29), date(2006, 7, 4), date(2006, 9, 4), date(2006, 11, 23), date(2006, 12, 25)},
    2007: {date(2007, 1, 1), date(2007, 1, 2), date(2007, 1, 15), date(2007, 2, 19), date(2007, 4, 6), date(2007, 5, 28), date(2007, 7, 4), date(2007, 9, 3), date(2007, 11, 22), date(2007, 12, 25)},
    2008: {date(2008, 1, 1), date(2008, 1, 21), date(2008, 2, 18), date(2008, 3, 21), date(2008, 5, 26), date(2008, 7, 4), date(2008, 9, 1), date(2008, 11, 27), date(2008, 12, 25)},
    2009: {date(2009, 1, 1), date(2009, 1, 19), date(2009, 2, 16), date(2009, 4, 10), date(2009, 5, 25), date(2009, 7, 3), date(2009, 9, 7), date(2009, 11, 26), date(2009, 12, 25)},
    2010: {date(2010, 1, 1), date(2010, 1, 18), date(2010, 2, 15), date(2010, 4, 2), date(2010, 5, 31), date(2010, 7, 5), date(2010, 9, 6), date(2010, 11, 25), date(2010, 12, 24)},
    2011: {date(2011, 1, 17), date(2011, 2, 21), date(2011, 4, 22), date(2011, 5, 30), date(2011, 7, 4), date(2011, 9, 5), date(2011, 11, 24), date(2011, 12, 26)},
    2012: {date(2012, 1, 2), date(2012, 1, 16), date(2012, 2, 20), date(2012, 4, 6), date(2012, 5, 28), date(2012, 7, 4), date(2012, 9, 3), date(2012, 10, 29), date(2012, 10, 30), date(2012, 11, 22), date(2012, 12, 25)},
    2013: {date(2013, 1, 1), date(2013, 1, 21), date(2013, 2, 18), date(2013, 3, 29), date(2013, 5, 27), date(2013, 7, 4), date(2013, 9, 2), date(2013, 11, 28), date(2013, 12, 25)},
    2014: {date(2014, 1, 1), date(2014, 1, 20), date(2014, 2, 17), date(2014, 4, 18), date(2014, 5, 26), date(2014, 7, 4), date(2014, 9, 1), date(2014, 11, 27), date(2014, 12, 25)},
    2015: {date(2015, 1, 1), date(2015, 1, 19), date(2015, 2, 16), date(2015, 4, 3), date(2015, 5, 25), date(2015, 7, 3), date(2015, 9, 7), date(2015, 11, 26), date(2015, 12, 25)},
    2016: {date(2016, 1, 1), date(2016, 1, 18), date(2016, 2, 15), date(2016, 3, 25), date(2016, 5, 30), date(2016, 7, 4), date(2016, 9, 5), date(2016, 11, 24), date(2016, 12, 26)},
    2017: {date(2017, 1, 2), date(2017, 1, 16), date(2017, 2, 20), date(2017, 4, 14), date(2017, 5, 29), date(2017, 7, 4), date(2017, 9, 4), date(2017, 11, 23), date(2017, 12, 25)},
    2018: {date(2018, 1, 1), date(2018, 1, 15), date(2018, 2, 19), date(2018, 3, 30), date(2018, 5, 28), date(2018, 7, 4), date(2018, 9, 3), date(2018, 11, 22), date(2018, 12, 5), date(2018, 12, 25)},
    2019: {date(2019, 1, 1), date(2019, 1, 21), date(2019, 2, 18), date(2019, 4, 19), date(2019, 5, 27), date(2019, 7, 4), date(2019, 9, 2), date(2019, 11, 28), date(2019, 12, 25)},
    2020: {date(2020, 1, 1), date(2020, 1, 20), date(2020, 2, 17), date(2020, 4, 10), date(2020, 5, 25), date(2020, 7, 3), date(2020, 9, 7), date(2020, 11, 26), date(2020, 12, 25)},
    2021: {date(2021, 1, 1), date(2021, 1, 18), date(2021, 2, 15), date(2021, 4, 2), date(2021, 5, 31), date(2021, 7, 5), date(2021, 9, 6), date(2021, 11, 25), date(2021, 12, 24)},
    2022: {date(2022, 1, 17), date(2022, 2, 21), date(2022, 4, 15), date(2022, 5, 30), date(2022, 6, 20), date(2022, 7, 4), date(2022, 9, 5), date(2022, 11, 24), date(2022, 12, 26)},
    2023: {date(2023, 1, 2), date(2023, 1, 16), date(2023, 2, 20), date(2023, 4, 7), date(2023, 5, 29), date(2023, 6, 19), date(2023, 7, 4), date(2023, 9, 4), date(2023, 11, 23), date(2023, 12, 25)},
    2024: {date(2024, 1, 1), date(2024, 1, 15), date(2024, 2, 19), date(2024, 3, 29), date(2024, 5, 27), date(2024, 6, 19), date(2024, 7, 4), date(2024, 9, 2), date(2024, 11, 28), date(2024, 12, 25)},
    2025: {date(2025, 1, 1), date(2025, 1, 9), date(2025, 1, 20), date(2025, 2, 17), date(2025, 4, 18), date(2025, 5, 26), date(2025, 6, 19), date(2025, 7, 4), date(2025, 9, 1), date(2025, 11, 27), date(2025, 12, 25)},
    2026: {date(2026, 1, 1), date(2026, 1, 19), date(2026, 2, 16), date(2026, 4, 3), date(2026, 5, 25), date(2026, 6, 19), date(2026, 7, 3), date(2026, 9, 7), date(2026, 11, 26), date(2026, 12, 25)},
    2027: {date(2027, 1, 1), date(2027, 1, 18), date(2027, 2, 15), date(2027, 3, 26), date(2027, 5, 31), date(2027, 6, 18), date(2027, 7, 5), date(2027, 9, 6), date(2027, 11, 25), date(2027, 12, 24)},
}
EARLY_CLOSES: dict[int, set[date]] = {
    2024: {date(2024, 7, 3), date(2024, 11, 29), date(2024, 12, 24)},
    2025: {date(2025, 7, 3), date(2025, 11, 28), date(2025, 12, 24)},
    2026: {date(2026, 11, 27), date(2026, 12, 24)},
    2027: {date(2027, 11, 26)},
}
OPEN_T = time(9, 30)
CLOSE_T = time(16, 0)
EARLY_CLOSE_T = time(13, 0)


def is_holiday(d: date) -> bool:
    return d in HOLIDAYS.get(d.year, set())


def is_trading_day(d: date) -> bool:
    return d.weekday() < 5 and not is_holiday(d)


def calendar_known(d: date) -> bool:
    return d.year in HOLIDAYS


def session_bounds(d: date) -> tuple[datetime, datetime] | None:
    """(open, close) in UTC for a trading day, None on a closed day."""
    if not is_trading_day(d):
        return None
    close_t = EARLY_CLOSE_T if d in EARLY_CLOSES.get(d.year, set()) else CLOSE_T
    o = datetime.combine(d, OPEN_T, tzinfo=NY).astimezone(timezone.utc)
    c = datetime.combine(d, close_t, tzinfo=NY).astimezone(timezone.utc)
    return o, c


def previous_trading_day(d: date) -> date:
    d = d - timedelta(days=1)
    while not is_trading_day(d):
        d -= timedelta(days=1)
    return d


def next_trading_day(d: date) -> date:
    d = d + timedelta(days=1)
    while not is_trading_day(d):
        d += timedelta(days=1)
    return d


def last_completed_session(now: datetime) -> date:
    """The most recent trading day whose close is already in the past."""
    ny = now.astimezone(NY)
    d = ny.date()
    b = session_bounds(d)
    if b is not None and now >= b[1]:
        return d
    return previous_trading_day(d)


def session_state(now: datetime) -> dict:
    """Where the US cash session stands right now."""
    ny = now.astimezone(NY)
    d = ny.date()
    b = session_bounds(d)
    if b is None:
        phase = "holiday" if is_holiday(d) else "weekend"
    elif now < b[0]:
        phase = "pre"
    elif now < b[1]:
        phase = "open"
    else:
        phase = "post"
    nxt = next_trading_day(d) if phase in ("holiday", "weekend", "post") else d
    nb = session_bounds(nxt)
    return {
        "exchange": "NYSE",
        "timezone": "America/New_York",
        "phase": phase,
        "is_open": phase == "open",
        "today_is_trading_day": b is not None,
        "early_close": d in EARLY_CLOSES.get(d.year, set()),
        "last_completed_session": last_completed_session(now).isoformat(),
        "next_open_utc": nb[0].strftime("%Y-%m-%dT%H:%M:%SZ") if nb else None,
        "calendar_known": calendar_known(d),
        "local_time": ny.strftime("%Y-%m-%d %H:%M %Z"),
    }


def bond_extra_closures(year: int) -> set[date]:
    """Bond-market (SIFMA) full closes on days the NYSE trades (B6, 2026-09-18):
    Columbus Day (second Monday of October) and Veterans Day (11 Nov; a Sunday
    date closes the Monday). FRED publishes no Treasury yield for these days,
    so the rates series must not count them as missed prints.

    Before 1974 the dates differed, as the stored DGS10 days show (FRED prints
    no Treasury yield on a bond holiday; desk/frame-3-api, plan S-12):
    Columbus Day was 12 October through 1970 (a Sunday closed the Monday, a
    Saturday nothing), and Veterans Day the fourth Monday of October in
    1971–1973 only; the bond market was back on 11 November from 1974, four
    years before the federal date."""
    oct1 = date(year, 10, 1)
    first_monday = oct1 + timedelta(days=(7 - oct1.weekday()) % 7)
    out: set[date] = set()
    if year <= 1970:
        columbus = date(year, 10, 12)
        if columbus.weekday() == 6:
            columbus += timedelta(days=1)
        if columbus.weekday() < 5:
            out.add(columbus)
    else:
        out.add(first_monday + timedelta(days=7))
    if 1971 <= year <= 1973:
        out.add(first_monday + timedelta(days=21))
    else:
        vet = date(year, 11, 11)
        if vet.weekday() == 6:
            vet += timedelta(days=1)
        if vet.weekday() < 5:
            out.add(vet)
    return out


def is_bond_trading_day(d: date) -> bool:
    return is_trading_day(d) and d not in bond_extra_closures(d.year)


def previous_bond_trading_day(d: date) -> date:
    d = d - timedelta(days=1)
    while not is_bond_trading_day(d):
        d -= timedelta(days=1)
    return d


def bond_business_days_between(a: date, b: date) -> int:
    """Bond-market trading days strictly after a up to and including b (b ≥ a)."""
    if b <= a:
        return 0
    n, d = 0, a
    while d < b:
        d += timedelta(days=1)
        if is_bond_trading_day(d):
            n += 1
    return n


def business_days_between(a: date, b: date) -> int:
    """Trading days strictly after a up to and including b (b ≥ a)."""
    if b <= a:
        return 0
    n, d = 0, a
    while d < b:
        d += timedelta(days=1)
        if is_trading_day(d):
            n += 1
    return n


def first_friday(year: int, month: int) -> date:
    d = date(year, month, 1)
    while d.weekday() != 4:
        d += timedelta(days=1)
    return d


def month_add(d: date, months: int) -> date:
    y, m = divmod(d.month - 1 + months, 12)
    return date(d.year + y, m + 1, 1)
